### ISSUE TITLE
no implicit conversion of Module into String on basic example

### ISSUE THREAD

**Issue by brianbancroft** [tigrish/i18n-spec#24]
Hi there, 

I have been trying to use the first example to test this library's suitability for testing yaml files, and I am unable to carry out the basic 'hello world' example for testing a locale file. The following block is what I used:

`spec/i18n/locales_spec.rb`
```ruby
require 'rails_helper'

RSpec.describe I18n do
  describe "config/locales/en.yml" do
    it { is_expected.to be_parseable }
  end
end

```

And my error message is as follows: 

```sh
1) I18n config/locales/en.yml should be parseable
     Failure/Error: it { is_expected.to be_parseable }

     TypeError:
       no implicit conversion of Module into String
```

And I also have a `config/locales/en.yml` file with the following content:

```yml
en:
  default_mailer:
    subject: "Message from %{name}"
    from_name: "%{name} Team"
```

Finally, I'm using the following versions:
Globalize: 5.1.0.beta2
rails-i18n: 5
rails: 5.1

If this is user error on my part, I'd be happy to offer an update the docs with a clear example on the Readme so that other jr devs will find less of a barrier to adoption. Thanks in advance for taking the time to read!

**Comment by legendetm** [comment]
You are getting the error, because RSpec `subject` is `I18n` not `"config/locales/en.yml"`. 

You have 3 options:
1. Use `RSpec.describe "config/locales/en.yml"`
2. Set subject explicitly `subject { "config/locales/en.yml" }`
```
RSpec.describe I18n do
  describe "en" do
    subject { "config/locales/en.yml" }
    it { is_expected.to be_parseable }
  end
end
```
3. Use `expect("config/locales/en.yml" ).to` syntax instead of `is_expected.to`

**Comment by brianbancroft** [comment]
Thanks! I've since moved on, but I'll forward this to the relevant party. Closing the issue.
